CREATE TABLE IF NOT EXISTS HABILIDADES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    nivel VARCHAR(255),
    portafolio_id BIGINT,
    FOREIGN KEY (portafolio_id) REFERENCES PORTAFOLIO(id)
);
